// <auto-generated />
namespace Shop.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FillProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FillProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201304270550084_FillProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
