// <auto-generated />
namespace Shop.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201304270542139_CreateProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
