// <auto-generated />
namespace Shop.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateVendors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateVendors));
        
        string IMigrationMetadata.Id
        {
            get { return "201304271145282_CreateVendors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
