// <auto-generated />
namespace Shop.Services.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SetRequiredFiledsFotProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetRequiredFiledsFotProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201304191635453_SetRequiredFiledsFotProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
